### ISSUE TITLE
SparqlResults dump with unbound variable

### ISSUE THREAD

**Issue by ianmillard** [njh/easyrdf#112]
If you do a sparql query which (erroneously?) selects a variable which does not appear in the query body, you get an unhelpful exception when using the dump() method to view the results.

Eg the following -- `SELECT ?person ?name ?email WHERE { ?person foaf:name ?name }`

In Sparql/Result.php [line 175](https://github.com/njh/easyrdf/blob/e1dcbb1ddc44985c5516f7b559a499c9e2629dfc/lib/EasyRdf/Sparql/Result.php#L175)  there is no guarantee that `$row->$field` actually exists.

I guess this may also occur if you have optional bindings?

Either way should probably test that `$row->$field` actually exists before calling `->dumpValue()` on it, and output an empty cell (or the text "null"?) if there is no value to dump?

**Comment by youboutna** [comment]
Dear Nicholas,
I want to use easyRDF library but i have a problem with sparql result .
i resume : 
print $results->dump(true); return all rdf file.
	print $results->getStatus(); return :  Call to undefined method EasyRdf_Graph::getStatus() ?

here is my query : 

	$client = new EasyRdf_Sparql_Client($queryUri);
		$query = 'SELECT ?processName WHERE {
?process a oboe-core:Observation ; oboe-core:ofEntity anaee-france_ontology:VsoilProcess ; oboe-core:hasMeasurement ?measurement .
?measurement a oboe-core:Measurement ; oboe-core:usesStandard anaee-france_ontology:VsoilProcessNamingStandard ; oboe-core:ofCharacteristic oboe-core:Name ; oboe-core:hasValue ?processName .
} LIMIT 2';
		$results=$client->query($query,$updateUri = null);
		//print $results->dump(true);
		print $results->getStatus();

**Comment by njh** [comment]
@youboutna please can you raise a new issue if you have a question?
