### ISSUE TITLE
EasyRdf_Http_Client timeout parameter not effective

### ISSUE THREAD

**Issue by osma** [njh/easyrdf#202]
Hi!

I'm using EasyRdf to load data from an external Linked Data server as part of the process of generating HTML pages on the server. I'm worried about situations where the server responds slowly or not at all. In that case, I'd rather show a page with incomplete data instead of letting the user wait very long or forever for the page to generate.

I can use EasyRdf_Graph::load() to fetch the data, which is very convenient as it handles all the content negotiation stuff automatically. Behind the scenes it uses EasyRdf_Http_Client which has a default timeout of 10 seconds. But it seems that this timeout only applies to the initial connection (it is used as a parameter for fsockopen()). It is not applied if the server quickly accepts the connection but then takes a long time to respond with actual data.

Example code:

```
<?php

require_once 'vendor/autoload.php'; // load EasyRdf via Composer

$starttime = time();
$graph = new EasyRdf_Graph("http://fake-response.appspot.com/?sleep=50");
$graph->load();
echo $graph . "\n";
$endtime = time();
echo "request took " . ($endtime-$starttime) . " seconds.\n";
```

(I'm using the [Fake Response Server](http://www.seanshadmand.com/2012/06/21/fake-response-server-slow-response-time-generator/) by Sean Shadmand to simulate slow responses.)

Output of this script:
```
http://fake-response.appspot.com/?sleep=50
request took 50 seconds.
```

I think this could be fixed using strem_set_timeout() in EasyRdf_Http_Client, though my initial attempts at adding such calls didn't work.

This may be related to issue #133 (it should be easier to provide an alternative HTTP client implementation) and #150 (also appears to be a timeout issue with the HTTP client). But I think everyone would benefit if the default EasyRdf_Http_Client included smarter timeout handling. If you think this would be a good idea, I can try to provide an implementation.

**Comment by osma** [comment]
Thanks for the update. Sounds good to me, though Guzzle requires PHP 5.4 so you will have to leave 5.3 support behind.

I tested Guzzle with the equivalent code and it does make use of timeouts:

```php
require 'vendor/autoload.php';

$starttime = time();
$client = new GuzzleHttp\Client();
$response = $client->get("http://fake-response.appspot.com/?sleep=50", [
  'config' => [
    'timeout' => 10
  ]
]);
echo $response;
$endtime = time();
echo "request took " . ($endtime-$starttime) . " seconds.\n";
```

This throws an exception after 10 seconds as expected, instead of waiting for the full 50 seconds.

**Comment by indeyets** [comment]
@osma Guzzle3 is 5.3 compatible

**Comment by osma** [comment]
Ah, right, so you're planning to stick to Guzzle3. Good to know - and I don't have to upgrade the PHP (5.3.3) on my CentOS 6 production servers or my Ubuntu 12.04 workstation just yet :)

I tested Guzzle 3.9.2 as well to see how it handles timeouts. With the following code, I get the expected behavior i.e. an exception after 10 seconds:

```php
require 'vendor/autoload.php';

$starttime = time();
$client = new Guzzle\Http\Client();
$request = $client->get("http://fake-response.appspot.com/?sleep=50",
  array(),
  array('timeout' => 10)
);
$response = $request->send();
echo $response->getBody();
$endtime = time();
echo "request took " . ($endtime-$starttime) . " seconds.\n";
```
