### ISSUE TITLE
Turning Sparql result into a graph

### ISSUE THREAD

**Issue by hms35** [njh/easyrdf#226]
Hello,
 Is there a prefered way to convert a result (from a Sparql query) into a graph ?

Thanks for your answer !
HM.

**Comment by njh** [comment]
Best to use a CONSTRUCT query - this will return RDF triples that will automatically be put into an EasyRdf_Graph for you.

**Comment by hms35** [comment]
Hi, and thanks for answering. 
Unfortunately, I can't obtain this behaviour. According to the source, the type of the client's 'request' method is given by the content-type of the store's response : if its "application/sparql-results*" we get a Result, otherwise we get a Graph. The fact is, I can't get any other Content-type but 'application-sparql-results-*' from the store. I'm looking into its config to see if i can change this.

**Comment by hms35** [comment]
Hi,
 It appears that the store i'm using (BigData) doesn't send anything else but "application/sparql-results(+json, +xml), as told by the client Accept headers. Is it possible to think about another way to get a Graph as a return of a CONSTRUCT query ?

Thanks !

**Comment by njh** [comment]
That sounds like a bug in BigData - can you report it to them?

EasyRdf should allow you to force a specific parse type to overcome problems like this, but unfortunately it isn't currently possible. 

One way to get round it would be to make a (long) SPARQL URL and then fetch and parse it using EasyRdf_Graph.

**Comment by hms35** [comment]
Hi, 
So with the new proposed update, a way to process is to override the parseResponseToQuery in order to handle the server response differently. Thanks for this, i'll process this way.

**Comment by indeyets** [comment]
@hms35 this is a hack-style solution for cases when actual data does not correspond to mime-type header. the proper solution would be to have heuristics in place, which will kick-in if default parser fails (I didn't file this as enhancement yet).

I am not 100% sure any of these cover your case. Is there a public endpoint which acts the way you describe? I could use it for tests.

Another possible direction would be to fine-tune our `Accept` headers depending on type of the query. We could remove `application/sparql-results` for `CONSTRUCT` queries, as technically we can accept them, our end-user probably doesn't want us to

**Comment by indeyets** [comment]
no matter what is the original usecase, it would be cool to have a high-level approach to converting between a 3-column (s-p-o) `EasyRdf\Sparql\Result` and `EasyRdf\Graph`.

@hms35 was that your original desire? I guess we were too distracted by fixing bugs (of which there are still some)

**Comment by hms35** [comment]
Hi, sorry for the late answer.
 My original desire was to get a graph from a CONSTRUCT query. Wouldn't it make sense to have a construct method that returns a Graph ?

Thanks !
HM.

**Comment by indeyets** [comment]
@hms35 I'll try to implement a fix for #231 today. that should be the most relevant issue for your case

**Comment by hms35** [comment]
@indeyets Great ! Thanks !

**Comment by indeyets** [comment]
@hms35 done. can you test it?

**Comment by hms35** [comment]
@indeyets I'm getting a graph from the query method now. all good !

**Comment by bdecarne** [comment]
6314d6ae66b6eeae086278e0a4878a9754aceb5e didn't solved the problem with bigdata : when you send "accept/json" to bigdata, it return Content-type "application/sparql-results+json"

I need to re-register the rdfxml format to make it work :

```

Format::register(
    'rdfxml',
    'RDF/XML',
    'http://www.w3.org/TR/rdf-syntax-grammar',
    array(
        'application/rdf+xml' => 1.1
    ),
    array('rdf', 'xrdf')
);
```
