### ISSUE TITLE
EasyRdf 0.10 Client is not compatible with Zend\Http\Client

### ISSUE THREAD

**Issue by indeyets** [njh/easyrdf#230]
ZF2 changed signatures of some of the methods. I didn't notice this during initial port.
We should add tests and update our part of the code.

There is a problem with `$client->setHeaders()` method (doesn't accept 2 strings as parameters anymore), but there might be others too

**Comment by indeyets** [comment]
this task is a bit more difficult than I expected, as `Zend\Http` is very different from `Zend_Http`.

I'm going to close this as WONTFIX if there are not volunteers (@njh ?) and proceed to implementation via Guzzle3 (newer versions require php 5.4+) as that was a long-term plan anyway

**Comment by njh** [comment]
Yes, this is a Won't Fix. Lets concentrate on Guzzle
