### ISSUE TITLE
Use different Accept headers for different types of queries

### ISSUE THREAD

**Issue by indeyets** [njh/easyrdf#231]
`Sparql\Client` adds everything we can handle as `Accept` headers in every http-request. It would be better to limit advertised types depending on the query type. 

Technically, we can parse anything we have a parser for, but…

spec [says](http://www.w3.org/TR/sparql11-query/#QueryForms)

> Formats such as SPARQL 1.1 Query Results JSON Format, SPARQL Query Results XML Format or SPARQL 1.1 Query Results CSV and TSV Formats can be used to serialize the result set from a SELECT query or the boolean result of an ASK query.

on the other hand, usage of "SPARQL Query Results" formats for representing graphs (result of `CONSTRUCT` and `DESCRIBE` queries) is ambiguous.

I propose to:

1. detect type of the query
2. send "SPARQL Query Results" accept-headers for `SELECT` and `ASK` queries
2. send Graph-related accept-headers for `CONSTRUCT` and `DEFINE` queries

**Comment by njh** [comment]
"detect type of the query"

I originally avoided this because I was concerned that it was difficult to do reliably.
But the regex you created doesn't look too bad :)

**Comment by indeyets** [comment]
I also did a fallback to old behavior in case parsing fails :)
