### ISSUE TITLE
JSON-LD parser issue

### ISSUE THREAD

**Issue by patrickmj** [njh/easyrdf#238]
I'm trying to do the following to try out JSON-LD parsing, but getting this error:

Fatal error: Class 'ML\JsonLD\JsonLD' not found in /var/www/DplaGraph/vendor/easyrdf/easyrdf/lib/EasyRdf/Parser/JsonLdImplementation.php on line 72

1	0.0004	233344	{main}( )	../test.php:0
2	0.0007	275496	EasyRdf_Graph->parse( )	../test.php:104
3	0.0014	318392	EasyRdf_Parser_JsonLd->parse( )

JSON-LD example from http://json-ld.org/

`
$jsonld = '
{
  "@context": "http://json-ld.org/contexts/person.jsonld",
  "@id": "http://dbpedia.org/resource/John_Lennon",
  "name": "John Lennon",
  "born": "1940-10-09",
  "spouse": "http://dbpedia.org/resource/Cynthia_Lennon"
}

';
`
in this PHP

```php
$graph = new EasyRdf_Graph();
$graph->parse($jsonld, 'jsonld');
$turtle = $graph->serialise('turtle');
echo $turtle;
```

Pulled in EasyRdf via composer on March 8 2015.

Maybe the latest isn't built in to the composer files yet, or is there something else I'm missing?

Broader context is building up to reading <a href='http://dp.la/info/developers/codex/responses/'>responses from DPLA API</a> into a graph as the ultimate goal.

Thoughts and guidance much appreciated!

**Comment by Tpt** [comment]
Have you installed https://packagist.org/packages/ml/json-ld ?

**Comment by indeyets** [comment]
@patrickmj just as @Tpt mentioned, you need to add following to `require` section of your `composer.json`:

```
 "ml/json-ld": "~1.0"
```

JSON-LD support is a soft-dependency

**Comment by patrickmj** [comment]
my bad! Thanks much!
