### ISSUE TITLE
Graph : a possible problem about property deletion

### ISSUE THREAD

**Issue by hms35** [njh/easyrdf#239]
Hello,
 I think there is an issue concerning the methods `deleteSingleProperty` and `getSingleProperty` of the `Graph` class : on the first, when a value is provided, and found in the graph, it is actually removed using  `unset` on the index array. But if you later try to access to the same value, after checking that the array is not empty, the `getSingleProperty` just tries to access the `0` index of the index array, which was possibly unset. Can we think of :
 - either using an `array_splice` when deleting method, 
 - or seeking for the first set index when getting the property?

Thanks for your reply !

**Comment by indeyets** [comment]
thank you for the report! this is a bug, indeed
