### ISSUE TITLE
MIME-type text/xml unsupported

### ISSUE THREAD

**Issue by DJakosa** [njh/easyrdf#240]
Sometimes a server returns RDF-document as text/xml. I've managed to solve error by registering text/xml under rdfxml format in Format.php:584. Is there a better way?
![image](https://cloud.githubusercontent.com/assets/7360893/6697497/2e81408e-ccf1-11e4-8a29-be0299079997.png)

**Comment by njh** [comment]
No, I think this is probably a good idea.
I have added it in 0b66d335ccca380076d14858c128fd2b99546153
