### ISSUE TITLE
using => shortand in n3 files

### ISSUE THREAD

**Issue by hmsuchier** [njh/easyrdf#246]
Hello,
 Is it possible to read n3 files using the => shorthand (described here http://www.w3.org/TeamSubmission/n3/#shorthand ) with EasyRdf n3 parser ?

Thanks in advance !
HM.

**Comment by njh** [comment]
Hello,

Sorry N3 is not supported by EasyRdf.
In fact N3 isn't even RDF - it is a super-set of RDF.

We are sticking to official standards, such as Turtle.

nick.
