### ISSUE TITLE
Q: use this for creating forms?

### ISSUE THREAD

**Issue by webbird** [njh/easyrdf#250]
Hi there, I am looking for a solution that lets me auto-create forms based on the schema.org schemas. What I need:

* A list of available schemas and variations, for example Event -> Business, ..., Person -> ...
* After the user has chosen ('Event' -> 'Business'), a list of available properties (startDate, endDate, ...)

I played around with the examples at schema.org and also created an example using my own formbuilder that would work, but I don't like to create form definitions for all classes manually. Do you think easyrdf is the right thing for me? I would use it either for creating the forms on the fly, or to auto-create them once by converting the definitions to something I can use (formbuilder config files).

**Comment by njh** [comment]
Hello @webbird 

Yes, I think EasyRdf is suitable for this. I have not tried but it should be possible to import the schema.org definitions and then generate a form based on it.

This example is probably the closest - it is a form for creating a FOAF document:
https://github.com/njh/easyrdf/blob/0.9.0/examples/foafmaker.php

nick.

**Comment by webbird** [comment]
Great, I will have a look at it. I am creating a plugin for a CMS and it would be a great solution to have EasyRdf for the hard work. :D I can start with schema.org and add others later.
