### ISSUE TITLE
Turtle serialiser: small bug 

### ISSUE THREAD

**Issue by coreation** [njh/easyrdf#252]
In the edge case of having the following as a literal:

Something something.... 
edge case silly useless end quote"

Results in the following Turtle serialisation:

"""Something something.... 
edge case silly useless end quote""""

Which is incorrect, the last quote should be escaped. I think this can be tracked down to [this](https://github.com/njh/easyrdf/blob/master/lib/Serialiser/Turtle.php#L84) line, where you might want to add a rule where any trailing double quotes should be escaped?

**Comment by njh** [comment]
Thanks for reporting.

Are you able to submit a PR with a test and fix?

**Comment by coreation** [comment]
Sure thing!

**Comment by coreation** [comment]
So this is a quick implementation, but I do want to write an additional test for it.
When I run the test however (php test/EasyRdf/Serialiser/TurtleTest.php) I get this:

PHP Fatal error:  Class 'EasyRdf\Http\Client' not found in /Users/jan/Sites/easyrdf/test/EasyRdf/Http/MockClient.php on line 43

Seems to me the the Client class wasn't properly namespaced or something? 
Should I run this test differently?

**Comment by napoleta** [comment]
REMOVE ME

2015-09-10 23:10 GMT+02:00 Jan Vansteenlandt <notifications@github.com>:

**Comment by coreation** [comment]
Hey @njh, just made a pull request with fix and test! See https://github.com/njh/easyrdf/pull/253

**Comment by njh** [comment]
Fixed in #253
