### ISSUE TITLE
text/plain is send in accept header, but response is not supported

### ISSUE THREAD

**Issue by sandervd** [njh/easyrdf#259]
Hi, first of all, I'm fairly new to the whole 'semantic' world, so please forgive me any rookie mistakes...

I've encountered the following situation:
Triple store supports the application/sparql-results+xml and text/plain
The following code sets results in an Accept header being set of text/plain with a preference of 0.9

`EasyRdf_Format::register(
    'ntriples',
    'N-Triples',
    'http://www.w3.org/TR/n-triples/',
    array(
        'application/n-triples' => 1.0,
        'text/plain' => 0.9,
        'text/ntriples' => 0.9,
        'application/ntriples' => 0.9,
        'application/x-ntriples' => 0.9
    ),
    array('nt')
);`

This results in a final Accept header of:

> Accept: application/ld+json,application/n-triples,application/sparql-results+json,application/json,application/x-httpd-php-source,application/x-ntriples;q=0.9,text/ntriples;q=0.9,application/ntriples;q=0.9,text/plain;q=0.9,application/rdf+json;q=0.9,text/json;q=0.9,text/turtle;q=0.8,application/sparql-results+xml;q=0.8,application/rdf+xml;q=0.8,application/turtle;q=0.7,application/x-turtle;q=0.7,application/xhtml+xml;q=0.4,text/html;q=0.4

Some queries to explain the problem:
> curl -i -H "Accept:text/plain" --data-urlencode "query=SELECT ?s ?p ?o WHERE { ?s ?p ?o . } LIMIT 1" http://dbpedia.org/sparql`

> curl -i -H "Accept:application/sparql-results+xml" --data-urlencode "query=SELECT ?s ?p ?o WHERE { ?s ?p ?o . } LIMIT 1" http://dbpedia.org/sparql

> curl -i -H "Accept:application/sparql-results+json" --data-urlencode "query=SELECT ?s ?p ?o WHERE { ?s ?p ?o . } LIMIT 1" http://dbpedia.org/sparql

So when application/rdf+json is unsupported, the accept with the second preference is text/plain...
The response of this is however unsupported.

Is there a specific reason text/plain is in the list of Accept?

**Comment by njh** [comment]
A SELECT query will return a tabular result - much like an SQL query. The results will either be application/sparql-results+xml or application/sparql-results+json.

A CONSTRUCT query returns RDF triples. These can be any of the types listed in the EasyRdf_Format - including ntriples.

I wouldn't recommend describing any machine-readable format as text/plain - only human readable documents.

**Comment by sandervd** [comment]
Hi @njh, thanks for your lightning fast reply!

Ok, I think I'm following so far...
So the same accept header is used for both SELECT and CONSTRUCT, right?
```
// Tell the server which response formats we can parse
        $accept = EasyRdf_Format::getHttpAcceptHeader(
            array(
              'application/sparql-results+json' => 1.0,
              'application/sparql-results+xml' => 0.8
            )
        );
```
But shouldn't the SELECT Accept types have a higher priority in this case, to avoid that the endpoint is tempted to reply in text/plain?
(a CONSTRUCT could use any of the formats, but a SELECT should stick to either response-json or xml)

**Comment by njh** [comment]
Yes, there is probably more that could be done for the client to inform the server the response type it is expecting.

But without parsing the query, it is hard to know what the response type should be - at the time I decided not to do that. And in-theory it is up to the server to decide the response format that it returned. The accept list just contains the formats that it is capable of decoding.

My preferred solution would be to remove 'text/plain' from the list of accepted formats; but there are some servers out there that don't use the proper MIME type for n-triples.
