### ISSUE TITLE
sparql query 

### ISSUE THREAD

**Issue by zaky2016** [njh/easyrdf#264]
good evning 
pleas be kined with me. i'm new to this.
i have created a decision ontology, [enter image description here][1] i need to interrogate this ontology from java using jena.
for example i want to select one of the methods where the number of actions is les then 5 and the type of the problem is (rank) ... should  i create individuals  to slect a method ??
i'm going to use this in a java application ... letter on, the user will input the type of the problem and the number of actions. can i pass this to variables to use in the query ?
![image](https://cloud.githubusercontent.com/assets/18519831/14590741/1afa136e-04fa-11e6-9552-52568243e1e4.png)

**Comment by njh** [comment]
EasyRDF is a PHP library.

It has nothing to do with Java or Jena.
