### ISSUE TITLE
Could use variable on insert data

### ISSUE THREAD

**Issue by cokorda** [njh/easyrdf#266]
Hi,

I would like to insert data into the jena using variable.  However it keep give me error.
   `    $kabupaten = $_POST['Denpasar'];` 
//setup prefix
`EasyRdf_Namespace::set ('thk' ,  'http://dpch.oss.web.id/Bali/TriHitaKarana.owl#');`

//setup end-point
`$client = new EasyRdf_Sparql_Client('http://dpch.oss.web.id:3030/thk/update');`

//insert-data
`$client->update(
        'INSERT DATA {
thk:$kabupaten a thk:Kabupaten }');`

The error is

> Fatal error: Uncaught exception 'EasyRdf_Exception' with message 'HTTP request for SPARQL query failed: Error 400: Parse error:..................

> easyrdf/lib/EasyRdf/Sparql/Client.php:290 Stack trace: #0 

Could you please assist us on how to solve this error?
Thanks

Rai

**Comment by njh** [comment]
Hello,

PHP does not perform variable interpolation when using single quotes (').
Swich to double quotes (") and it should work.

http://php.net/manual/en/language.types.string.php#language.types.string.parsing

nick.

**Comment by cokorda** [comment]
Hi Nick,

Thank you so much for your help.

Warm regards,

Rai
