### ISSUE TITLE
Failed to parse RDF from URL http://viaf.org/viaf/87772061/ 

### ISSUE THREAD

**Issue by nichtich** [njh/easyrdf#268]
All other RDF parsers/tools can get RDF from http://viaf.org/viaf/87772061/ (for instance [W3C RDF validator](https://www.w3.org/RDF/Validator/rdfval?URI=http%3A%2F%2Fviaf.org%2Fviaf%2F87772061%2F&PARSE=Parse+URI%3A+&TRIPLES_AND_GRAPH=PRINT_TRIPLES&FORMAT=PNG_EMBED)) but EasyRDF fails with error message " Invalid argument supplied for foreach()" (tested at http://www.easyrdf.org/converter).

**Comment by njh** [comment]
Weirdly VIAF doesn't return Turtle (or an error) if you request it:

curl -H "Accept: text/turtle" -v 'http://viaf.org/viaf/87772061/'

```
> GET http://viaf.org/viaf/87772061/ HTTP/1.1
> Host: viaf.org
> User-Agent: curl/7.44.0
> Proxy-Connection: Keep-Alive
> Accept: text/turtle
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: Apache-Coyote/1.1
< Content-Type: text/xml
< Date: Tue, 14 Jun 2016 10:36:39 GMT
< Connection: close
< 
<?xml version="1.0"  encoding="UTF-8"?> 
```

So I guess this a bug in the RDF/XML parser.

**Comment by njh** [comment]
Actually it looks like a bug in the VIAF content negotiation code. The above isn't RDF, it is some other kind of XML.

Explicitly requesting RDF works:

http://www.easyrdf.org/converter?uri=http://viaf.org/viaf/87772061/rdf.xml
