### ISSUE TITLE
Get label of a given dbpedia resource

### ISSUE THREAD

**Issue by NadaBen** [njh/easyrdf#269]
Hello,
I want to get for a given Dbpedia Resource it's Rdfs: label, for example for: http://fr.dbpedia.org/resource/Automobile I want to get just Automobile,
I tried with  easy RDF Graph label function : 

                     ' $label= new \EasyRdf\Graph;
               $re= $label->label('http://fr.dbpedia.org/resource/Automobile');
               var_dump($re)'

but it gives me null as result

**Comment by njh** [comment]
I think you are getting the concepts of Graph, Resource and Label confused.

Graph: the document/container of information
Resource: a single entity / node in the graph
Label: property type linking a resource to the a string

The following works for me:
```
<?php
 
  require_once realpath(__DIR__.'/..')."/vendor/autoload.php";

  $uri = 'http://fr.dbpedia.org/resource/Automobile';
  $graph = \EasyRdf\Graph::newAndLoad($uri);
  $resource = $graph->resource($uri);

  echo "English Label: " . $resource->label('en') . "\n";
  echo "French Label: " . $graph->label($uri, 'fr') . "\n";
```

Output:
```
English Label: Motor vehicle
French Label: Automobile
```
