### ISSUE TITLE
tag 0.10.x

### ISSUE THREAD

**Issue by Aedius** [njh/easyrdf#270]
Hello, 

I would like to use this project, but i need namespace and can't use the branch master ( like i found in some project Oo )

Is it possible to just create a tag 0.10.0-rc1 from master ?

Thanks

**Comment by njh** [comment]
Hi,

I have created:
https://github.com/njh/easyrdf/tree/0.10.0-alpha.1

nick.

**Comment by Aedius** [comment]
over 9000 thanks
