### ISSUE TITLE
parsing n-quads

### ISSUE THREAD

**Issue by omidmaldar** [njh/easyrdf#274]
is it possible to parse n-quads files using EasyRDF? I'm wondering how may I use these kinds of datasets: [WebDataCommons](http://webdatacommons.org/structureddata/2015-11/stats/how_to_get_the_data.html)
thanks

**Comment by njh** [comment]
Query answered here:
https://groups.google.com/d/msg/easyrdf/Qs93ZxJ8f1o/FU0JTne3AwAJ

**Comment by omidmaldar** [comment]
thank you @njh
