### ISSUE TITLE
Uncaught exception 'EasyRdf_Exception' with message 'No URI given to load() and the graph does not have a URI.' in C:\wamp\www\app\rdf\EasyRdf\Graph.php on line 275

### ISSUE THREAD

**Issue by rabiam04** [njh/easyrdf#290]
hi,
I am using a local rdf file, i got above error, here is code which i m using

$graph = new EasyRdf_Graph(); 
     $graph->parseFile("faculty.rdf"); 
	 $graph->load();
$me = $graph->primaryTopic();
echo "My name is: ".$me->get('fd:name')."\n";

Please guide, thanks in advance :)

**Comment by njh** [comment]
This was also asked on the Google Groups mailing list:
https://groups.google.com/d/msg/easyrdf/ZskAVJW9YXs/kDtCdbo_BwAJ

**Comment by njh** [comment]
Reply posted to mailing list:
https://groups.google.com/d/msg/easyrdf/ZskAVJW9YXs/291gK2TGCgAJ
