### ISSUE TITLE
ERROR: No parser class available for format: png

### ISSUE THREAD

**Issue by mhabsaoui** [njh/easyrdf#293]
Hi,
I am encountering this first time error returned from EasyRDF :/

![capture du 2018-02-15 17-16-29](https://user-images.githubusercontent.com/18755135/36267378-fe11522e-1273-11e8-862f-b1556aba024f.png)

I got this http status code on browser console : **500 Internal Server Error**

We have no clue where the hell comes this "png" thing from => only text parsing usually, not media files actually at all...

hint:   
![capture du 2018-02-15 13-06-51](https://user-images.githubusercontent.com/18755135/36256202-311c18f6-1252-11e8-996d-1b76c31ac306.png)

Browsers tested => Firefox + Chrome

It seems we got some CC license pngs images in *.RDF files...

`<cc:License rdf:about="http://creativecommons.org/licenses/by/4.0/">
      <cc:requires rdf:resource="http://creativecommons.org/ns#Notice"/>
      <cc:requires rdf:resource="http://creativecommons.org/ns#Attribution"/>
      <foaf:logo rdf:resource="http://i.creativecommons.org/l/by/4.0/80x15.png"/>
      <foaf:logo rdf:resource="http://i.creativecommons.org/l/by/4.0/88x31.png"/>
      <dc:title xml:lang="en">Attribution 4.0 International</dc:title>
      <cc:permits rdf:resource="http://creativecommons.org/ns#Reproduction"/>
      <cc:permits rdf:resource="http://creativecommons.org/ns#Distribution"/>
      <cc:permits rdf:resource="http://creativecommons.org/ns#DerivativeWorks"/>
   </cc:License>`

... But this bug is returned by EasyRdf, even if there are no vocabularies at all in our TDB (Fuseki + Skosmos) or the searched term in empty/blank. So it seems unrelated to data at all...

PS: I have also started to discuss this bug here =>  https://github.com/NatLibFi/Skosmos/issues/711. But as it seems to mainly concern EasyRDF, I hope you can help to go beyond this... 

Thanks.

**Comment by njh** [comment]
Sorry, there isn't really enough information here to work out if this is a problem with EasyRdf. I'm afraid I have no knowledge of Skosmos, what it does or how it works.

From the limited information given, I can only imagine there is some code somewhere doing something like this:
```
  $graph = new EasyRdf_Graph('http://i.creativecommons.org/l/by/4.0/80x15.png');
  $graph->load();
```

If you are able to provide a snippet of EasyRDF PHP that demonstrates this fault, then I should be able to investigate.

**Comment by mhabsaoui** [comment]
> Sorry, there isn't really enough information here to work out if this is a problem with EasyRdf. 
> If you are able to provide a snippet of EasyRDF PHP that demonstrates this fault, then I should be able to investigate.

I'll glad to give more info, all we got is what Easyrdf returns. 

Is there any option to turn on so the logs are more explicit or a log file generated by easyrdf ?

Thanks.

**Comment by njh** [comment]
EasyRdf is a library written in PHP and runs entirely on the server - the browser shouldn't be involved.

EasyRdf doesn't do any logging itself - it is up to the application to do logging, as requirements vary enormously.

**Comment by mhabsaoui** [comment]
> it is up to the application to do logging

I have tried to log any PHP errors by editing the "/etc/php5/apache2/php.ini" to enable php errors logging into  a file (/var/log/php-errors.log). But nothing is logged...

Any suggestion about PHP logging ?

Thanks

**Comment by mhabsaoui** [comment]
Well I got it solved.

Now I wonder if there is anything related to the searching strategy of EasyRdf or something that may caused this "Bug"?

Thanks
