### ISSUE TITLE
SPARQL query validation

### ISSUE THREAD

**Issue by rezacsedu** [njh/easyrdf#298]
Hi,

I was wondering if I can use EasyRdf for SPARQL query validation? 
I mean, once a query is submitted, is there's any way to validate that the query is syntactically correct?

**Comment by njh** [comment]
No, EasyRdf does not parse or validate SPARQL queries - it just passed them to a SPARQL server for processing.

It is possible to send the query to the server and then check if the server returns an error - but you will be executing the query.
