### ISSUE TITLE
New release 0.9.2

### ISSUE THREAD

**Issue by claudiu-cristea** [njh/easyrdf#299]
0.9.1 is from 27 February 2015. There are 102 commits since then.

**Comment by Daniel-KM** [comment]
Yes, it is important to update and to fix this tool regularly, as it is a core one for many projects.

**Comment by Daniel-KM** [comment]
There are some pull requests too, and some iinteresting commits in forks too. for example to speed parsing heavily.

**Comment by Daniel-KM** [comment]
An interesting patch may be https://github.com/acdh-oeaw/easyrdf/commit/545cb24f8734fce019f1de996197093889154e02, that increase time upload (not fully tested).

**Comment by Daniel-KM** [comment]
An interesting patch may be https://github.com/acdh-oeaw/easyrdf/commit/545cb24f8734fce019f1de996197093889154e02, that dereases time parsing (not fully tested).

**Comment by PulsarFox** [comment]
Any news for new release ? The last download release on EasyRdf Website is from 2014-12-03

**Comment by demiankatz** [comment]
Just adding my support for a new release -- I have multiple projects that rely on the namespaced version of the code, and I'd love to be able to pin them to a known stable version. Thanks for all of the work on this project -- it is very valuable!

**Comment by jungleran** [comment]
Subscribing

**Comment by k00ni** [comment]
@njh Can you tell us, if you plan to make a new release anytime soon?

**Comment by njh** [comment]
It is unlikely that there will ever be a version 0.9.2 (using the PHP 5.2 namespacing).

Discussion about releasing version 1.0.0 (with PHP 5.3+ namespacing) is now covered in #320.
