### ISSUE TITLE
query against EasyRDF_Graph object?

### ISSUE THREAD

**Issue by robertbbb** [njh/easyrdf#308]
Is it possible to run a SPARQL query against the graph loaded in an EasyRDF_Graph? It currently seems that queries can only be applied to SPARQL Clients and those clients cannot be connected to a graph object, only to an endpoint.

**Comment by njh** [comment]
No, it is not possible.

The intended use for EasyRDF is to run SPARQL queries in a remote SPARQL engine and then use EasyRDF to display the results.
