### ISSUE TITLE
Can't get query result

### ISSUE THREAD

**Issue by silviolorusso** [njh/easyrdf#310]
Hello, I sent the following query to the database, and I'm sure is successful because I checked the presence of the object via phpmyadmin:

`INSERT INTO <http://p-dpa.net/work/g/> {
	<http://p-dpa.net/work/g/> <http://purl.org/dc/terms/creator> <http://p-dpa.net/creator/jack-strange/> .
}`

But when I try to retrieve the query with the following code I get an empty array:

`SELECT ?url
WHERE	{
	<http://p-dpa.net/work/g/> <http://purl.org/dc/terms/creator> ?url .
}`

How is that possible?

**Comment by njh** [comment]
* Which SPARQL database are you using?
* Have you been able to successfully do the same thing using [curl](https://curl.haxx.se) or [Postman](https://www.getpostman.com) or a CLI [sparql client](https://github.com/tialaramex/sparql-query)?

**Comment by njh** [comment]
No response, closing.
