### ISSUE TITLE
Creation of a json format for Dumps 

### ISSUE THREAD

**Issue by lawrencenull** [njh/easyrdf#315]
It would be incredibly useful to just dump an object as standard json, 

        echo $graph->dump($format = "json");

**Comment by njh** [comment]
Have you tried the RDF/JSON serialisation format?

```php
echo $graph->serialise('json');
```

Spec here:
http://web.archive.org/web/20100801085122/http://n2.talis.com/wiki/RDF_JSON_Specification

**Comment by njh** [comment]
No response; closing issue
